"""Add all tables for phase 3 and 4

Revision ID: 17b1974d0918
Revises: 3ae3c899b99a
Create Date: 2026-06-14 03:36:33.125113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17b1974d0918'
down_revision: Union[str, Sequence[str], None] = '3ae3c899b99a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_code', sa.String(length=64), nullable=False),
    sa.Column('order_codes', sa.JSON(), nullable=False),
    sa.Column('goods_schedules', sa.JSON(), nullable=False),
    sa.Column('total_distance', sa.DECIMAL(precision=12, scale=3), nullable=False),
    sa.Column('total_time', sa.DECIMAL(precision=12, scale=3), nullable=False),
    sa.Column('total_goods', sa.Integer(), nullable=False),
    sa.Column('score', sa.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('algorithm_type', sa.String(length=32), server_default='traditional', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('replan_reason', sa.String(length=500), nullable=True),
    sa.Column('is_replan', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['global_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_schedules_schedule_code'), 'global_schedules', ['schedule_code'], unique=True)
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_node_code'), 'nodes', ['node_code'], unique=True)
    op.create_table('dispatch_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_code', sa.String(length=64), nullable=False),
    sa.Column('global_schedule_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('demo_mode', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('l0_l1_dispatch_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('l1_l2_dispatch_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('algorithm_type', sa.String(length=32), server_default='traditional', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('replan_reason', sa.String(length=500), nullable=True),
    sa.Column('is_replan', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['global_schedule_id'], ['global_schedules.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['dispatch_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_batches_batch_code'), 'dispatch_batches', ['batch_code'], unique=True)
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('driver_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('license_type', sa.String(length=8), nullable=False),
    sa.Column('shift', sa.String(length=64), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='idle', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_driver_code'), 'drivers', ['driver_code'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_code', sa.String(length=64), nullable=False),
    sa.Column('destination_node_id', sa.Integer(), nullable=False),
    sa.Column('time_window', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['destination_node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_code'), 'orders', ['order_code'], unique=True)
    op.create_table('sorting_centers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('max_storage_time', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id')
    )
    op.create_table('storage_centers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('inventory', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_code', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('capacity', sa.DECIMAL(precision=10, scale=3), nullable=False),
    sa.Column('energy_type', sa.String(length=16), nullable=False),
    sa.Column('vehicle_type', sa.String(length=32), server_default='normal', nullable=False),
    sa.Column('capability_tags', sa.JSON(), nullable=True),
    sa.Column('last_arrived_node_id', sa.Integer(), nullable=False),
    sa.Column('last_arrived_longitude', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('last_arrived_latitude', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='idle', nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['last_arrived_node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_vehicle_code'), 'vehicles', ['vehicle_code'], unique=True)
    op.create_table('goods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goods_code', sa.String(length=64), nullable=False),
    sa.Column('goods_name', sa.String(length=128), nullable=False),
    sa.Column('goods_type', sa.String(length=64), nullable=False),
    sa.Column('weight', sa.DECIMAL(precision=10, scale=3), nullable=False),
    sa.Column('volume', sa.DECIMAL(precision=10, scale=3), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending_pack', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_goods_code'), 'goods', ['goods_code'], unique=True)
    op.create_table('node_dispatches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dispatch_code', sa.String(length=64), nullable=False),
    sa.Column('dispatch_batch_id', sa.Integer(), nullable=False),
    sa.Column('level_phase', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('tasks', sa.JSON(), nullable=False),
    sa.Column('total_distance', sa.DECIMAL(precision=12, scale=3), nullable=False),
    sa.Column('total_time', sa.DECIMAL(precision=12, scale=3), nullable=False),
    sa.Column('algorithm_type', sa.String(length=32), server_default='traditional', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('replan_reason', sa.String(length=500), nullable=True),
    sa.Column('is_replan', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dispatch_batch_id'], ['dispatch_batches.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['node_dispatches.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_dispatches_dispatch_code'), 'node_dispatches', ['dispatch_code'], unique=True)
    op.create_table('packages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('package_code', sa.String(length=64), nullable=False),
    sa.Column('weight', sa.DECIMAL(precision=10, scale=3), nullable=False),
    sa.Column('volume', sa.DECIMAL(precision=10, scale=3), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending_pack', nullable=False),
    sa.Column('from_node_id', sa.Integer(), nullable=False),
    sa.Column('to_node_id', sa.Integer(), nullable=False),
    sa.Column('from_longitude', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('from_latitude', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('to_longitude', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('to_latitude', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('goods_items', sa.JSON(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('dispatch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dispatch_id'], ['node_dispatches.id'], ),
    sa.ForeignKeyConstraint(['from_node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['global_schedules.id'], ),
    sa.ForeignKeyConstraint(['to_node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packages_package_code'), 'packages', ['package_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_packages_package_code'), table_name='packages')
    op.drop_table('packages')
    op.drop_index(op.f('ix_node_dispatches_dispatch_code'), table_name='node_dispatches')
    op.drop_table('node_dispatches')
    op.drop_index(op.f('ix_goods_goods_code'), table_name='goods')
    op.drop_table('goods')
    op.drop_index(op.f('ix_vehicles_vehicle_code'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_table('storage_centers')
    op.drop_table('sorting_centers')
    op.drop_index(op.f('ix_orders_order_code'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_drivers_driver_code'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_dispatch_batches_batch_code'), table_name='dispatch_batches')
    op.drop_table('dispatch_batches')
    op.drop_index(op.f('ix_nodes_node_code'), table_name='nodes')
    op.drop_table('nodes')
    op.drop_index(op.f('ix_global_schedules_schedule_code'), table_name='global_schedules')
    op.drop_table('global_schedules')
    # ### end Alembic commands ###
